// ============================================================================
// mockData.ts
// Database completo di paesi e capitali mondiali,
// suddiviso per livello di difficoltà:
// ============================================================================

import type { CountryData, Difficulty } from './types';
export const COUNTRIES: CountryData[] = [

  // ==========================================================================
  // FACILE / MEDIO — 98 paesi - BUSINESS CLASS
  // ==========================================================================

  // Europa
  { id: 'it', country: 'Italia',          capital: 'Roma',       difficulty: 'facile', flagCode: 'IT' },
  { id: 'fr', country: 'Francia',         capital: 'Parigi',     difficulty: 'facile', flagCode: 'FR' },
  { id: 'de', country: 'Germania',        capital: 'Berlino',    difficulty: 'facile', flagCode: 'DE' },
  { id: 'es', country: 'Spagna',          capital: 'Madrid',     difficulty: 'facile', flagCode: 'ES' },
  { id: 'gb', country: 'Regno Unito',     capital: 'Londra',     difficulty: 'facile', flagCode: 'GB' },
  { id: 'gr', country: 'Grecia',          capital: 'Atene',      difficulty: 'facile', flagCode: 'GR' },
  { id: 'at', country: 'Austria',         capital: 'Vienna',     difficulty: 'facile', flagCode: 'AT' },
  { id: 'be', country: 'Belgio',          capital: 'Bruxelles',  difficulty: 'facile', flagCode: 'BE' },
  { id: 'hu', country: 'Ungheria',        capital: 'Budapest',   difficulty: 'facile', flagCode: 'HU' },
  { id: 'ie', country: 'Irlanda',         capital: 'Dublino',    difficulty: 'facile', flagCode: 'IE' },
  { id: 'dk', country: 'Danimarca',       capital: 'Copenaghen', difficulty: 'facile', flagCode: 'DK' },
  { id: 'pt', country: 'Portogallo',             capital: 'Lisbona',      difficulty: 'facile', flagCode: 'PT' },
  { id: 'nl', country: 'Paesi Bassi',            capital: 'Amsterdam',    difficulty: 'facile', flagCode: 'NL' },
  { id: 'se', country: 'Svezia',                 capital: 'Stoccolma',    difficulty: 'facile', flagCode: 'SE' },
  { id: 'no', country: 'Norvegia',               capital: 'Oslo',         difficulty: 'facile', flagCode: 'NO' },
  { id: 'fi', country: 'Finlandia',              capital: 'Helsinki',     difficulty: 'facile', flagCode: 'FI' },
  { id: 'pl', country: 'Polonia',                capital: 'Varsavia',     difficulty: 'facile', flagCode: 'PL' },
  { id: 'cz', country: 'Repubblica Ceca',        capital: 'Praga',        difficulty: 'facile', flagCode: 'CZ' },
  { id: 'ro', country: 'Romania',                capital: 'Bucarest',     difficulty: 'facile', flagCode: 'RO' },
  { id: 'ua', country: 'Ucraina',                capital: 'Kiev',         difficulty: 'facile', flagCode: 'UA' },
  { id: 'by', country: 'Bielorussia',            capital: 'Minsk',        difficulty: 'facile', flagCode: 'BY' },
  { id: 'rs', country: 'Serbia',                 capital: 'Belgrado',     difficulty: 'facile', flagCode: 'RS' },
  { id: 'hr', country: 'Croazia',                capital: 'Zagabria',     difficulty: 'facile', flagCode: 'HR' },
  { id: 'bg', country: 'Bulgaria',               capital: 'Sofia',        difficulty: 'facile', flagCode: 'BG' },
  { id: 'sk', country: 'Slovacchia',             capital: 'Bratislava',   difficulty: 'facile', flagCode: 'SK' },
  { id: 'ba', country: 'Bosnia ed Erzegovina',   capital: 'Sarajevo',     difficulty: 'facile', flagCode: 'BA' },
  { id: 'is', country: 'Islanda',                capital: 'Reykjavík',    difficulty: 'facile', flagCode: 'IS' },
  { id: 'ch', country: 'Svizzera',               capital: 'Berna',              difficulty: 'facile', flagCode: 'CH' },
  { id: 'al', country: 'Albania',                capital: 'Tirana',             difficulty: 'facile', flagCode: 'AL' },
  { id: 'ad', country: 'Andorra',                capital: 'Andorra la Vella',   difficulty: 'facile', flagCode: 'AD' },
  { id: 'lu', country: 'Lussemburgo',          capital: 'Lussemburgo',            difficulty: 'avanzato', flagCode: 'LU' },
  { id: 'mt', country: 'Malta',                capital: 'La Valletta',            difficulty: 'avanzato', flagCode: 'MT' },
  { id: 'li', country: 'Liechtenstein',        capital: 'Vaduz',                  difficulty: 'avanzato', flagCode: 'LI' },
  { id: 'sm', country: 'San Marino',           capital: 'Città di San Marino',    difficulty: 'avanzato', flagCode: 'SM' },
  { id: 'va', country: 'Città del Vaticano',   capital: 'Città del Vaticano',     difficulty: 'avanzato', flagCode: 'VA' },
  { id: 'cy', country: 'Cipro',                capital: 'Nicosia',                difficulty: 'avanzato', flagCode: 'CY' },
  { id: 'ee', country: 'Estonia',              capital: 'Tallinn',                difficulty: 'facile', flagCode: 'EE' },
  { id: 'lv', country: 'Lettonia',             capital: 'Riga',                   difficulty: 'facile', flagCode: 'LV' },
  { id: 'lt', country: 'Lituania',             capital: 'Vilnius',                difficulty: 'facile', flagCode: 'LT' },
  { id: 'mc', country: 'Monaco',               capital: 'Monaco',                 difficulty: 'facile', flagCode: 'MC' },

  // Americhe
  { id: 'us', country: 'Stati Uniti',     capital: 'Washington', difficulty: 'facile', flagCode: 'US' },
  { id: 'ca', country: 'Canada',          capital: 'Ottawa',     difficulty: 'facile', flagCode: 'CA' },
  { id: 'cu', country: 'Cuba',            capital: "L'Avana",    difficulty: 'facile', flagCode: 'CU' },
  { id: 'cl', country: 'Cile',            capital: 'Santiago',   difficulty: 'facile', flagCode: 'CL' },
  { id: 'ar', country: 'Argentina',              capital: 'Buenos Aires',        difficulty: 'facile', flagCode: 'AR' },
  { id: 'br', country: 'Brasile',                capital: 'Brasília',            difficulty: 'facile', flagCode: 'BR' },
  { id: 'mx', country: 'Messico',                capital: 'Città del Messico',   difficulty: 'facile', flagCode: 'MX' },
  { id: 'co', country: 'Colombia',               capital: 'Bogotà',              difficulty: 'facile', flagCode: 'CO' },
  { id: 've', country: 'Venezuela',              capital: 'Caracas',             difficulty: 'facile', flagCode: 'VE' },
  { id: 'pe', country: 'Perù',                   capital: 'Lima',                difficulty: 'facile', flagCode: 'PE' },
  { id: 'uy', country: 'Uruguay',                capital: 'Montevideo',          difficulty: 'facile', flagCode: 'UY' },
  { id: 'ec', country: 'Ecuador',                capital: 'Quito',               difficulty: 'facile', flagCode: 'EC' },
  { id: 'gt', country: 'Guatemala',              capital: 'Città del Guatemala', difficulty: 'facile', flagCode: 'GT' },
  { id: 'do', country: 'Repubblica Dominicana',  capital: 'Santo Domingo',       difficulty: 'facile', flagCode: 'DO' },
  { id: 'cr', country: 'Costa Rica',             capital: 'San José',            difficulty: 'facile', flagCode: 'CR' },
  { id: 'jm', country: 'Giamaica',               capital: 'Kingston',            difficulty: 'facile', flagCode: 'JM' },
  { id: 'ni', country: 'Nicaragua',              capital: 'Managua',             difficulty: 'facile', flagCode: 'NI' },
  { id: 'pa', country: 'Panama',                 capital: 'Ciudad de Panamá',    difficulty: 'facile', flagCode: 'PA' },
  { id: 'sv', country: 'El Salvador',            capital: 'San Salvador',        difficulty: 'facile', flagCode: 'SV' },

  // Africa
  { id: 'eg', country: 'Egitto',      capital: 'Il Cairo',      difficulty: 'facile', flagCode: 'EG' },
  { id: 'za', country: 'Sudafrica',   capital: 'Pretoria',      difficulty: 'facile', flagCode: 'ZA' },
  { id: 'dz', country: 'Algeria',     capital: 'Algeri',        difficulty: 'facile', flagCode: 'DZ' },
  { id: 'ma', country: 'Marocco',     capital: 'Rabat',         difficulty: 'facile', flagCode: 'MA' },
  { id: 'tn', country: 'Tunisia',     capital: 'Tunisi',        difficulty: 'facile', flagCode: 'TN' },
  { id: 'ly', country: 'Libia',       capital: 'Tripoli',       difficulty: 'facile', flagCode: 'LY' },
  { id: 'ng', country: 'Nigeria',     capital: 'Abuja',         difficulty: 'facile', flagCode: 'NG' },
  { id: 'ke', country: 'Kenya',       capital: 'Nairobi',       difficulty: 'facile', flagCode: 'KE' },
  { id: 'et', country: 'Etiopia',     capital: 'Addis Abeba',   difficulty: 'facile', flagCode: 'ET' },
  { id: 'sd', country: 'Sudan',       capital: 'Khartum',       difficulty: 'facile', flagCode: 'SD' },
  { id: 'sn', country: 'Senegal',     capital: 'Dakar',         difficulty: 'facile', flagCode: 'SN' },
  { id: 'dj', country: 'Gibuti',      capital: 'Gibuti',        difficulty: 'facile', flagCode: 'DJ' },

  // Asia
  { id: 'ru', country: 'Russia',          capital: 'Mosca',      difficulty: 'facile', flagCode: 'RU' },
  { id: 'cn', country: 'Cina',            capital: 'Pechino',    difficulty: 'facile', flagCode: 'CN' },
  { id: 'jp', country: 'Giappone',        capital: 'Tokyo',      difficulty: 'facile', flagCode: 'JP' },
  { id: 'in', country: 'India',           capital: 'Nuova Delhi',difficulty: 'facile', flagCode: 'IN' },
  { id: 'kr', country: 'Corea del Sud',   capital: 'Seoul',      difficulty: 'facile', flagCode: 'KR' },
  { id: 'sa', country: 'Arabia Saudita',  capital: 'Riad',       difficulty: 'facile', flagCode: 'SA' },
  { id: 'th', country: 'Thailandia',      capital: 'Bangkok',    difficulty: 'facile', flagCode: 'TH' },
  { id: 'sg', country: 'Singapore',       capital: 'Singapore',  difficulty: 'facile', flagCode: 'SG' },
  { id: 'tr', country: 'Turchia',             capital: 'Ankara',        difficulty: 'facile', flagCode: 'TR' },
  { id: 'ir', country: 'Iran',                capital: 'Teheran',       difficulty: 'facile', flagCode: 'IR' },
  { id: 'iq', country: 'Iraq',                capital: 'Baghdad',       difficulty: 'facile', flagCode: 'IQ' },
  { id: 'pk', country: 'Pakistan',            capital: 'Islamabad',     difficulty: 'facile', flagCode: 'PK' },
  { id: 'af', country: 'Afghanistan',         capital: 'Kabul',         difficulty: 'facile', flagCode: 'AF' },
  { id: 'sy', country: 'Siria',               capital: 'Damasco',       difficulty: 'facile', flagCode: 'SY' },
  { id: 'lb', country: 'Libano',              capital: 'Beirut',        difficulty: 'facile', flagCode: 'LB' },
  { id: 'jo', country: 'Giordania',           capital: 'Amman',         difficulty: 'facile', flagCode: 'JO' },
  { id: 'ae', country: 'Emirati Arabi Uniti', capital: 'Abu Dhabi',     difficulty: 'facile', flagCode: 'AE' },
  { id: 'qa', country: 'Qatar',               capital: 'Doha',          difficulty: 'facile', flagCode: 'QA' },
  { id: 'kp', country: 'Corea del Nord',      capital: 'Pyongyang',     difficulty: 'facile', flagCode: 'KP' },
  { id: 'vn', country: 'Vietnam',             capital: 'Hanoi',         difficulty: 'facile', flagCode: 'VN' },
  { id: 'my', country: 'Malaysia',            capital: 'Kuala Lumpur',  difficulty: 'facile', flagCode: 'MY' },
  { id: 'ph', country: 'Filippine',           capital: 'Manila',        difficulty: 'facile', flagCode: 'PH' },
  { id: 'id', country: 'Indonesia',           capital: 'Giacarta',      difficulty: 'facile', flagCode: 'ID' },
  { id: 'tw', country: 'Taiwan',              capital: 'Taipei',        difficulty: 'facile', flagCode: 'TW' },
  { id: 'kw', country: 'Emirato del Kuwait',  capital: 'Al Kuwait',     difficulty: 'facile', flagCode: 'KW' },

  // Oceania
  { id: 'au', country: 'Australia',   capital: 'Canberra',   difficulty: 'facile', flagCode: 'AU' },
  { id: 'nz', country: 'Nuova Zelanda', capital: 'Wellington', difficulty: 'facile', flagCode: 'NZ' },


  // ==========================================================================
  // AVANZATO — 90 paesi - FIRST CLASS
  // ==========================================================================

  // Europa
  { id: 'md', country: 'Moldova',              capital: 'Chișinău',           difficulty: 'avanzato', flagCode: 'MD' },
  { id: 'me', country: 'Montenegro',           capital: 'Podgorica',          difficulty: 'avanzato', flagCode: 'ME' },
  { id: 'mk', country: 'Macedonia del Nord',   capital: 'Skopje',             difficulty: 'avanzato', flagCode: 'MK' },
  { id: 'si', country: 'Slovenia',             capital: 'Lubiana',            difficulty: 'avanzato', flagCode: 'SI' },
  { id: 'xk', country: 'Kosovo',               capital: 'Pristina',           difficulty: 'avanzato', flagCode: 'XK' },

  // Americhe settentrionali e Caraibi
  { id: 'ag', country: 'Antigua e Barbuda',         capital: "Saint John's",  difficulty: 'avanzato', flagCode: 'AG' },
  { id: 'bs', country: 'Bahamas',                   capital: 'Nassau',         difficulty: 'avanzato', flagCode: 'BS' },
  { id: 'bb', country: 'Barbados',                  capital: 'Bridgetown',     difficulty: 'avanzato', flagCode: 'BB' },
  { id: 'bz', country: 'Belize',                    capital: 'Belmopan',       difficulty: 'avanzato', flagCode: 'BZ' },
  { id: 'dm', country: 'Dominica',                  capital: 'Roseau',         difficulty: 'avanzato', flagCode: 'DM' },
  { id: 'gd', country: 'Grenada',                   capital: "Saint George's", difficulty: 'avanzato', flagCode: 'GD' },
  { id: 'ht', country: 'Haiti',                     capital: 'Port-au-Prince', difficulty: 'avanzato', flagCode: 'HT' },
  { id: 'hn', country: 'Honduras',                  capital: 'Tegucigalpa',    difficulty: 'avanzato', flagCode: 'HN' },
  { id: 'kn', country: 'Saint Kitts e Nevis',       capital: 'Basseterre',     difficulty: 'avanzato', flagCode: 'KN' },
  { id: 'lc', country: 'Saint Lucia',               capital: 'Castries',       difficulty: 'avanzato', flagCode: 'LC' },
  { id: 'vc', country: 'Saint Vincent e Grenadine', capital: 'Kingstown',      difficulty: 'avanzato', flagCode: 'VC' },
  { id: 'tt', country: 'Trinidad e Tobago',         capital: 'Port of Spain',  difficulty: 'avanzato', flagCode: 'TT' },

  // Americhe meridionali
  { id: 'bo', country: 'Bolivia',       capital: 'Sucre',        difficulty: 'avanzato', flagCode: 'BO' },
  { id: 'gy', country: 'Guyana',        capital: 'Georgetown',   difficulty: 'avanzato', flagCode: 'GY' },
  { id: 'py', country: 'Paraguay',      capital: 'Asunción',     difficulty: 'avanzato', flagCode: 'PY' },
  { id: 'sr', country: 'Suriname',      capital: 'Paramaribo',   difficulty: 'avanzato', flagCode: 'SR' },

  // Africa
  { id: 'ao', country: 'Angola',                   capital: 'Luanda',          difficulty: 'avanzato', flagCode: 'AO' },
  { id: 'bj', country: 'Benin',                    capital: 'Porto-Novo',      difficulty: 'avanzato', flagCode: 'BJ' },
  { id: 'bw', country: 'Botswana',                 capital: 'Gaborone',        difficulty: 'avanzato', flagCode: 'BW' },
  { id: 'bf', country: 'Burkina Faso',             capital: 'Ouagadougou',     difficulty: 'avanzato', flagCode: 'BF' },
  { id: 'bi', country: 'Burundi',                  capital: 'Gitega',          difficulty: 'avanzato', flagCode: 'BI' },
  { id: 'cm', country: 'Camerun',                  capital: 'Yaoundé',         difficulty: 'avanzato', flagCode: 'CM' },
  { id: 'cv', country: 'Capo Verde',               capital: 'Praia',           difficulty: 'avanzato', flagCode: 'CV' },
  { id: 'cf', country: 'Repubblica Centrafricana', capital: 'Bangui',          difficulty: 'avanzato', flagCode: 'CF' },
  { id: 'td', country: 'Ciad',                     capital: "N'Djamena",       difficulty: 'avanzato', flagCode: 'TD' },
  { id: 'km', country: 'Comore',                   capital: 'Moroni',          difficulty: 'avanzato', flagCode: 'KM' },
  { id: 'cg', country: 'Repubblica del Congo',     capital: 'Brazzaville',     difficulty: 'avanzato', flagCode: 'CG' },
  { id: 'cd', country: 'Congo (RDC)',              capital: 'Kinshasa',        difficulty: 'avanzato', flagCode: 'CD' },
  { id: 'ci', country: "Costa d'Avorio",           capital: 'Yamoussoukro',    difficulty: 'avanzato', flagCode: 'CI' },
  { id: 'er', country: 'Eritrea',                  capital: 'Asmara',          difficulty: 'avanzato', flagCode: 'ER' },
  { id: 'sz', country: 'eSwatini',                 capital: 'Mbabane',         difficulty: 'avanzato', flagCode: 'SZ' },
  { id: 'ga', country: 'Gabon',                    capital: 'Libreville',      difficulty: 'avanzato', flagCode: 'GA' },
  { id: 'gm', country: 'Gambia',                   capital: 'Banjul',          difficulty: 'avanzato', flagCode: 'GM' },
  { id: 'gh', country: 'Ghana',                    capital: 'Accra',           difficulty: 'avanzato', flagCode: 'GH' },
  { id: 'gn', country: 'Guinea',                   capital: 'Conakry',         difficulty: 'avanzato', flagCode: 'GN' },
  { id: 'gq', country: 'Guinea Equatoriale',       capital: 'Ciudad de la Paz',    difficulty: 'avanzato', flagCode: 'GQ' },
  { id: 'gw', country: 'Guinea-Bissau',            capital: 'Bissau',          difficulty: 'avanzato', flagCode: 'GW' },
  { id: 'ls', country: 'Lesotho',                  capital: 'Maseru',          difficulty: 'avanzato', flagCode: 'LS' },
  { id: 'lr', country: 'Liberia',                  capital: 'Monrovia',        difficulty: 'avanzato', flagCode: 'LR' },
  { id: 'mg', country: 'Madagascar',               capital: 'Antananarivo',    difficulty: 'avanzato', flagCode: 'MG' },
  { id: 'mw', country: 'Malawi',                   capital: 'Lilongwe',        difficulty: 'avanzato', flagCode: 'MW' },
  { id: 'ml', country: 'Mali',                     capital: 'Bamako',          difficulty: 'avanzato', flagCode: 'ML' },
  { id: 'mr', country: 'Mauritania',               capital: 'Nouakchott',      difficulty: 'avanzato', flagCode: 'MR' },
  { id: 'mu', country: 'Mauritius',                capital: 'Port Louis',      difficulty: 'avanzato', flagCode: 'MU' },
  { id: 'mz', country: 'Mozambico',                capital: 'Maputo',          difficulty: 'avanzato', flagCode: 'MZ' },
  { id: 'na', country: 'Namibia',                  capital: 'Windhoek',        difficulty: 'avanzato', flagCode: 'NA' },
  { id: 'ne', country: 'Niger',                    capital: 'Niamey',          difficulty: 'avanzato', flagCode: 'NE' },
  { id: 'rw', country: 'Ruanda',                   capital: 'Kigali',          difficulty: 'avanzato', flagCode: 'RW' },
  { id: 'st', country: 'São Tomé e Príncipe',      capital: 'São Tomé',        difficulty: 'avanzato', flagCode: 'ST' },
  { id: 'sc', country: 'Seychelles',               capital: 'Victoria',        difficulty: 'avanzato', flagCode: 'SC' },
  { id: 'sl', country: 'Sierra Leone',             capital: 'Freetown',        difficulty: 'avanzato', flagCode: 'SL' },
  { id: 'so', country: 'Somalia',                  capital: 'Mogadiscio',      difficulty: 'avanzato', flagCode: 'SO' },
  { id: 'ss', country: 'Sudan del Sud',            capital: 'Giuba',           difficulty: 'avanzato', flagCode: 'SS' },
  { id: 'tz', country: 'Tanzania',                 capital: 'Dodoma',          difficulty: 'avanzato', flagCode: 'TZ' },
  { id: 'tg', country: 'Togo',                     capital: 'Lomé',            difficulty: 'avanzato', flagCode: 'TG' },
  { id: 'ug', country: 'Uganda',                   capital: 'Kampala',         difficulty: 'avanzato', flagCode: 'UG' },
  { id: 'zm', country: 'Zambia',                   capital: 'Lusaka',          difficulty: 'avanzato', flagCode: 'ZM' },
  { id: 'zw', country: 'Zimbabwe',                 capital: 'Harare',          difficulty: 'avanzato', flagCode: 'ZW' },

  // Asia
  { id: 'am', country: 'Armenia',      capital: 'Yerevan',              difficulty: 'avanzato', flagCode: 'AM' },
  { id: 'az', country: 'Azerbaigian',  capital: 'Baku',                 difficulty: 'avanzato', flagCode: 'AZ' },
  { id: 'bh', country: 'Bahrein',      capital: 'Manama',               difficulty: 'avanzato', flagCode: 'BH' },
  { id: 'bd', country: 'Bangladesh',   capital: 'Dacca',                difficulty: 'avanzato', flagCode: 'BD' },
  { id: 'bt', country: 'Bhutan',       capital: 'Thimphu',              difficulty: 'avanzato', flagCode: 'BT' },
  { id: 'bn', country: 'Brunei',       capital: 'Bandar Seri Begawan',  difficulty: 'avanzato', flagCode: 'BN' },
  { id: 'kh', country: 'Cambogia',     capital: 'Phnom Penh',           difficulty: 'avanzato', flagCode: 'KH' },
  { id: 'ge', country: 'Georgia',      capital: 'Tbilisi',              difficulty: 'avanzato', flagCode: 'GE' },
  { id: 'kz', country: 'Kazakistan',   capital: 'Astana',               difficulty: 'avanzato', flagCode: 'KZ' },
  { id: 'kg', country: 'Kirghizistan', capital: 'Bishkek',              difficulty: 'avanzato', flagCode: 'KG' },
  { id: 'la', country: 'Laos',         capital: 'Vientiane',            difficulty: 'avanzato', flagCode: 'LA' },
  { id: 'mv', country: 'Maldive',      capital: 'Malé',                 difficulty: 'avanzato', flagCode: 'MV' },
  { id: 'mn', country: 'Mongolia',     capital: 'Ulaanbaatar',          difficulty: 'avanzato', flagCode: 'MN' },
  { id: 'mm', country: 'Myanmar',      capital: 'Naypyidaw',            difficulty: 'avanzato', flagCode: 'MM' },
  { id: 'np', country: 'Nepal',        capital: 'Kathmandu',            difficulty: 'avanzato', flagCode: 'NP' },
  { id: 'om', country: 'Oman',         capital: 'Mascate',              difficulty: 'avanzato', flagCode: 'OM' },
  { id: 'pw', country: 'Palau',        capital: 'Ngerulmud',            difficulty: 'avanzato', flagCode: 'PW' },
  { id: 'ox', country: 'Ossezia del Sud',      capital: 'Tskhinvali',   difficulty: 'avanzato', flagCode: 'GE' },
  { id: 'lk', country: 'Sri Lanka',    capital: 'Sri Jayawardenepura Kotte', difficulty: 'avanzato', flagCode: 'LK' },
  { id: 'tj', country: 'Tagikistan',   capital: 'Dushanbe',             difficulty: 'avanzato', flagCode: 'TJ' },
  { id: 'tl', country: 'Timor Est',    capital: 'Dili',                 difficulty: 'avanzato', flagCode: 'TL' },
  { id: 'tm', country: 'Turkmenistan', capital: 'Ashgabat',             difficulty: 'avanzato', flagCode: 'TM' },
  { id: 'uz', country: '',   capital: 'Tashkent',             difficulty: 'avanzato', flagCode: 'UZ' },
  { id: 'ye', country: 'Yemen',        capital: "Sana'a",               difficulty: 'avanzato', flagCode: 'YE' },

  // Oceania
  { id: 'fj', country: 'Figi',              capital: 'Suva',           difficulty: 'avanzato', flagCode: 'FJ' },
  { id: 'ki', country: 'Kiribati',          capital: 'Tarawa del Sud', difficulty: 'avanzato', flagCode: 'KI' },
  { id: 'mh', country: 'Isole Marshall',    capital: 'Majuro',         difficulty: 'avanzato', flagCode: 'MH' },
  { id: 'fm', country: 'Micronesia',        capital: 'Palikir',        difficulty: 'avanzato', flagCode: 'FM' },
  { id: 'nr', country: 'Nauru',             capital: 'Yaren',          difficulty: 'avanzato', flagCode: 'NR' },
  { id: 'pg', country: 'Papua Nuova Guinea',capital: 'Port Moresby',   difficulty: 'avanzato', flagCode: 'PG' },
  { id: 'ws', country: 'Samoa',             capital: 'Apia',           difficulty: 'avanzato', flagCode: 'WS' },
  { id: 'sb', country: 'Isole Salomone',    capital: 'Honiara',        difficulty: 'avanzato', flagCode: 'SB' },
  { id: 'to', country: 'Tonga',             capital: "Nuku'Alofa",     difficulty: 'avanzato', flagCode: 'TO' },
  { id: 'tv', country: 'Tuvalu',            capital: 'Funafuti',       difficulty: 'avanzato', flagCode: 'TV' },
  { id: 'vu', country: 'Vanuatu',           capital: 'Port Vila',      difficulty: 'avanzato', flagCode: 'VU' },
];

/** Restituisce tutte le voci appartenenti a un dato livello di difficoltà. */
export function getCountriesByDifficulty(difficulty: Difficulty): CountryData[] {
  return COUNTRIES.filter((c) => c.difficulty === difficulty);
}
